FROM restgym/deeprest-tool:1.0.0

# Copy API specifications into the tool image

COPY apis/alfresco/specifications/* /specifications/
COPY apis/bezkoder/specifications/* /specifications/
COPY apis/blog/specifications/* /specifications/
COPY apis/cassandra-management-api/specifications/* /specifications/
COPY apis/erc20/specifications/* /specifications/
COPY apis/features-service/specifications/* /specifications/
COPY apis/flightsearchapi/specifications/* /specifications/
COPY apis/flowable-process/specifications/* /specifications/
COPY apis/genome-nexus/specifications/* /specifications/
COPY apis/gestaohospitalar/specifications/* /specifications/
COPY apis/gravitee/specifications/* /specifications/
COPY apis/infrastructure/specifications/* /specifications/
COPY apis/kafka-rest/specifications/* /specifications/
COPY apis/keycloak/specifications/* /specifications/
COPY apis/languagetool/specifications/* /specifications/
COPY apis/liferay/specifications/* /specifications/
COPY apis/market/specifications/* /specifications/
COPY apis/microcks/specifications/* /specifications/
COPY apis/ncs/specifications/* /specifications/
COPY apis/nexus/specifications/* /specifications/
COPY apis/notebookmanager/specifications/* /specifications/
COPY apis/person-controller/specifications/* /specifications/
COPY apis/petclinic/specifications/* /specifications/
COPY apis/project-tracking-system/specifications/* /specifications/
COPY apis/quartzmanager/specifications/* /specifications/
COPY apis/realworld-backend-micronaut/specifications/* /specifications/
COPY apis/restcountries/specifications/* /specifications/
COPY apis/scs/specifications/* /specifications/
COPY apis/spring-kafka-producer/specifications/* /specifications/
COPY apis/spring-kafka-publisher/specifications/* /specifications/
COPY apis/traccar/specifications/* /specifications/
COPY apis/user-management/specifications/* /specifications/